### PR TITLE
Remove multi output

### PR DESCRIPTION
**Pull request by joto**
Removes the multi output as preparation for new middle implementations.

### CODE REVIEW

**Comment by pnorman** [comment]
👍 in principle, haven't reviewed that everything is removed.

**Comment by joto** [comment]
I compiled with coverage and went through the report, so I believe I found everything that can be removed.

**Comment by mmd-osm** [comment]
Some additional locations that could be removed now:
* https://github.com/joto/osm2pgsql/blob/remove-multi/docs/multi.md
* https://github.com/joto/osm2pgsql/blob/remove-multi/tests/common-options.hpp#L61-L67

**Comment by joto** [comment]
Thanks for your eagle eyes @mmd-osm, I have added a commit removing these.

**Pull request merged**
