### PR TITLE
Add link to readme to find OSM data

### PR DESCRIPTION
**Pull request by tpitale**
As a newbie, I went looking for the OSM data to load. This seems to be canonical place. I could be wrong. I _think_ a link would be helpful.

### CODE REVIEW

**Comment by pnorman** [comment]
planet.osm.org is the canonical place, but I'm not sure we should link to it. Most people will want to start with a third-party extract.

**Comment by tpitale** [comment]
Could we link to a wiki page or something to describe what third-party extracts are, and maybe some examples? I'm completely ignorant of these other data extracts.

Just trying to help out other newcomers, in the readme or wiki.

**Comment by lonvia** [comment]
planet.osm.org has links to extract providers on its main page. I think it's fair to add a link to it. Personal preference would be to add it in the 'Usage' section (which, by the way, confusingly talks about data.osm.pbf and planet-latest.osm.pbf).

**Comment by tpitale** [comment]
Not sure if the comment surrounding the link is appropriate …

**Pull request merged**
