### PR TITLE
Don't link with libstdc++

### PR DESCRIPTION
**Pull request by AMDmi3**
First, there's no need, as c++ compiler does this implicitly.
Next, this is erroneous as standard c++ library may be named differently (e.g. libc++ from llvm project).

### CODE REVIEW

**Comment by pnorman** [comment]
Builds on FreeBSD with clang, `--without-lockfree`

**Comment by AMDmi3** [comment]
> Builds on FreeBSD with clang, --without-lockfree

Yup, I'm going to update the port right away.

**Comment by pnorman** [comment]
> Yup, I'm going to update the port right away

I should also note that the current version builds on freebsd with clang --without-lockfree, it's just a check that we didn't have a regression

**Comment by AMDmi3** [comment]
Of course, I've added that flag to the port as it doesn't build otherwise.

**Pull request merged**
