### PR TITLE
Check that database is using UTF-8 encoding

### PR DESCRIPTION
**Pull request by joto**
Otherwise osm2pgsql might not work correctly.

### CODE REVIEW

**Review by pnorman — CHANGES_REQUESTED** [review]
This change will check the server encoding, not the database encoding.

Do we want to consider client encoding at all?

**Comment by joto** [comment]
> This change will check the server encoding, not the database encoding.

Is there a difference? When I create a database with `createdb -E xxx`, the settings returned for `server_encoding` is `xxx`, so I believe this is the correct way of checking the encoding.

> Do we want to consider client encoding at all?

Do we ever had problems with that? We could simply set the `client_encoding` in the connection string.

**Comment by pnorman** [comment]
> Is there a difference? When I create a database with `createdb -E xxx`, the settings returned for `server_encoding` is `xxx`, so I believe this is the correct way of checking the encoding.

Looks okay after testing. I didn't realize that pg_settings was per-DB.

> Do we ever had problems with that? We could simply set the client_encoding in the connection string.

We probably should if we're worried about non-UTF8 encodings.

**Comment by lonvia** [comment]
I've run into problems on machines where the database was UTF-8 but the cluster wasn't. It might just be because we don't set the client encoding. Usually the cluster ended up not being utf-8 because the machine itself wasn't configured for it.

**Comment by joto** [comment]
Addition PR for the client thing here: https://github.com/openstreetmap/osm2pgsql/pull/1840

**Review by pnorman — APPROVED** [review]

**Pull request merged**
