### PR TITLE
Update appveyor libs

### PR DESCRIPTION
**Pull request by lonvia**
just testing the CI

### CODE REVIEW

**Comment by lonvia** [comment]
This now compiles on Appveyor but there are three tests failing. There is some projection data missing which I don't know where to put and possibly there is an incompatibility with expat.

**Comment by alex85k** [comment]
In my case test-parse-xml2 needed libxml2.dll in dependencies (did not manage to get it static like expat).
Also seems that proj.lib is built as debug variant (may be incompatible on Windows, so the "MSVCRTD' conflicts with use of other libs", sometimes segfaults are related)

**Comment by lonvia** [comment]
@alex85k Any chance you can pick this up? I don't have access to a windows machine and therefore not the environment to rebuild anything. I have just copied together stuff from other builds. The current package contains:

 - boost, bzip2, expat, proj, wingetopt, zlib from the libosmium dependencies
 - liblua from the osrm dependencies

all from the mapbox build scripts. libxml isn't used anymore at all.

**Comment by alex85k** [comment]
OK, I'll try to make some some working variant from Mapbox dependencies, will also check libxml2 again.

**Comment by alex85k** [comment]
libxml2 was really unrelated
Copying all dlls helped to fix this build:
https://github.com/alex85k/osm2pgsql/commit/3840e5fda9af4abb5cea566736bbfa6310dec947
https://ci.appveyor.com/project/alex85k/osm2pgsql/build/1.0.136

Here is the repacked dependencies pack with fixed proj.4 (release libs), just in case
https://www.dropbox.com/s/02fwkj4jr161mpt/osm2pgsql_win_deps_release.7z?dl=0
(remove ``-DBZIP2_LIBRARY_RELEASE=C:/libs/lib/libbz2.lib -DZLIB_LIBRARY=C:\libs\lib\zlibwapi.lib`` to use it, I have renamed zlib and bzip2 libs.

**Comment by lonvia** [comment]
I've added your changes from #744 and uploaded the repacked library with the release version. And all checks pass. Many thanks to @alex85k and @BergWerkGIS for your help.

I would like to find a more permanent place for the library bundles that is accessible by other maintainers as well. @pnorman any suggestions?

**Comment by pnorman** [comment]
> I would like to find a more permanent place for the library bundles that is accessible by other maintainers as well. @pnorman any suggestions?

errol, S3, or github pages/releases on a dedicated repo. As a less desirable option, one of our personal sites.

**Comment by lonvia** [comment]
errol is good enough for now. Done.

**Pull request merged**
