### PR TITLE
fix printf formats for 64 bit values

### PR DESCRIPTION
**Pull request by alex85k**
Tried to fix https://github.com/openstreetmap/osm2pgsql/issues/468 . Is this correct?

### CODE REVIEW

**Comment by alex85k** [comment]
Incorrect. Fixing :)

**Comment by alex85k** [comment]
Strange. Travis does not build it at all...

**Comment by alex85k** [comment]
Seems to pass now.

**Comment by pnorman** [comment]
boost::format has bad performance (#398) but all these fprintfs are only run once. I'd be okay with changing these to boost::format, which I believe would avoid the formatting string issues completely.

We still need to find a logging library (#202), but just printing to stderr like before is good enough for now.

**Comment by pnorman** [comment]
Merging, and I'll look at doing a backport for 0.88.x. Pulling out fprintf can wait.

**Pull request merged**
