### PR TITLE
Added Ubuntu & macOS matrixes to GitHub Actions

### PR DESCRIPTION
**Pull request by hummeltech**
* Now also builds & tests on `Ubuntu 22.04` & `macOS 12`
  * `macOS 12` was just made [generally available](https://github.blog/changelog/2022-06-13-github-actions-macos-12-for-github-hosted-runners-is-now-generally-available/)
* Customize `Ubuntu Prerequisites` action
  * In order to later support:
    * Being re-used by `Test install` workflow
* Customize `Build and test` action
  * To support customizing:
    * Configuration options:
      * `BUILD_TESTS`
      * `CMAKE_OPTIONS`
      * `CXXFLAGS`
      * `INSTALL_PREFIX`
    * Build options:
      * `BUILD_PARALLEL_LEVEL`
      * `BUILD_TARGET`
      * `BUILD_TYPE`
      * `CMAKE_BUILD_OPTIONS`
  * In order to later support:
    * Being re-used by `Windows` job matrix in `CI` workflow
    * Being re-used by `Test install` workflow
* Also tuned `PostgreSQL` configuration for `macOS` ~~& `Windows`~~
  * To help speed up test runs (as was already done for `Ubuntu`)
* Moved `macOS Prerequisite` steps into new action
  * Including initial database setup (and new tuning)
* ~~Split `build-and-test` action into `build` & `test` (and added `install`)~~
  * ~~In order to re-use `build` action in `Test install` workflow~~
  * ~~And re-use `build` & `test` actions for `Windows` job~~

### CODE REVIEW

**Comment by lonvia** [comment]
Thank you for looking into latest Ubuntu. Unfortunately, you have added too many changes to the CI system in this single PR that  it is impossible to review the changes in a reasonable time. Can I ask you to break down the changes into chunks that cover one refactoring step at the time.

**Comment by hummeltech** [comment]
Yeah, sure thing. It's no problem, the best I can do is probably splitting out the Windows-related changes into a dependent pull request.

**Comment by hummeltech** [comment]
Alright @lonvia, I have reverted most everything I think. It might still be a bit difficult to inspect `.github/workflows/ci.yml`, but that's mostly because the previously distinct jobs were migrated from `jobs.{Job}` into `jobs.{macOS|Ubuntu}.strategy.matrix` in order to clean the configuration up (I.E. no longer specifying the exact same steps for every `Ubuntu` job).

Using [Hide whitespace](https://github.com/openstreetmap/osm2pgsql/pull/1684/files?w=1) might make it easier to inspect at least some of the changed files (when using GitHub's web interface).

**Comment by joto** [comment]
The best way to **not** get a PR looked at is to change formatting at the same time as changing anything else. Please don't do that. Nobody can follow that. Please make small changes, the smallest that can work on their own and explain what you are doing and why.

**Comment by hummeltech** [comment]
Good point @joto. Alright, I've taken care of that too!

**Comment by lonvia** [comment]
I'm going to close this as it is still too large to be reviewable and now also has conflicts with the main branch. If you want to have another go, please break it down into multiple PRs, so each change can be discussed separately.

**Pull request closed without merging**
