### PR TITLE
Lua function errors now trigger runtime exception

### LINKED ISSUE #664: Give a better error when a transform returns a non-string type
I had a multi backend transform which returned tags `{foo=true}`, and it reports the error

```
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_M_construct null not valid
```

This error doesn't give any clue that the problem is in the transform

### PR DESCRIPTION
**Pull request by mmd-osm**
I don't know exactly why errors in Lua processing are only sent to stderr and processing continues. There could be some nasty issues overflowing the stack and causing other types of corruption.

I have changed those messages to runtime errors now. Maybe there are some reasons why this doesn't make sense, in which case I'm happy to revert that part of this PR.

Also, I added some error handling for lua_tostring with details about incorrect data type. Instead of throwing some strange exception as in #664, processing now aborts with the following message.

_Osm2pgsql failed due to ERROR: Basic tag processing returned NULL value. Possibly this is due an incorrect data type 'boolean'._

Another example:

```lua
function filter_tags_generic(tags)
    local foo = 0

    local bar = {}

    bar[123] = function()
      return 123
    end

    if foo == 0 then
      return 0, bar
    end
```

Error message: _Osm2pgsql failed due to ERROR: Basic tag processing returned NULL value. Possibly this is due an incorrect data type 'function'._

Fixes #664

### CODE REVIEW

**Comment by mmd-osm** [comment]
> Any objections to changing to early fail here?

It not only changing to early fail, it really a question of failing or not failing at all. The current implementation silently discards _any_ errors raising in Lua processing. If you don't check your stderr job logs manually, you will never find out that a particular transformation might have an issue.

**Comment by mmd-osm** [comment]
As seen on https://help.openstreetmap.org/questions/64259/osm2pgsql-failed-due-to-error-failed-to-execute-lua-function:

@SomeoneElseOSM seems to be the first one to hit this stricter check: the previous z_order calculation logic had some issue ("attempt to perform arithmetic on field 'layer' (a string value)")  and the error message on osm2pgsql was easy to ignore. With the stricter check, the error message is no longer ignored, and the stylesheet needs to be fixed to use proper Lua syntax.
 
Code in question: https://github.com/SomeoneElseOSM/SomeoneElse-style/blob/master/style.lua#L16

**Comment by pnorman** [comment]
It's good to know that it's working - that code was always in error.

```
5*"4"
stdin:1: unexpected symbol near '5'
```

**Comment by mmd-osm** [comment]
Well, the code didn't really check, if the field contains a number. In many cases that's not really an issue if the value can be implicitly converted to a number. It fails though, when people use multiple values, like in `layer = 4;3`, or put in some other non-numeric value in there.

```lua
> print(5*"4")
20
> print(tonumber("4"))
4

```

```lua
> print(5*"4;3")
stdin:1: attempt to perform arithmetic on a string value
stack traceback:
	stdin:1: in main chunk
	[C]: in ?
> print(tonumber("4;3"))
nil

```

**Comment by SomeoneElseOSM** [comment]
@mmd-osm pull requests welcome :)

**Comment by mmd-osm** [comment]
@SomeoneElseOSM : just copy & paste from upstream osm carto, it's already implemented properly there.

**Comment by SomeoneElseOSM** [comment]
Oddly, I'm not able to reproduce https://github.com/SomeoneElseOSM/SomeoneElse-style/issues/5 locally with the latest version of osm2pgsql (with the "Failed to execute lua function for basic tag processing" text in it) and the dodgy style.lua with "z_order = 10*keyvalues["layer"]" in it.  I don't see the reported "Failed to execute" errors, even when I load data that has "layer=yes" in it (Oxfordshire, which contains https://www.openstreetmap.org/way/68346732).

Obviously I could correct the style.lua, but it'd be nice to know why the error doesn't occur for me first!  Any suggestions as to what to look at?  It's not some sort of alternate type of lua processing that I need to enable is it?  Currently I've just got a Kubuntu 18.04 laptop and followed https://wiki.openstreetmap.org/wiki/User:SomeoneElse/Ubuntu_1804_tileserver_load#Install_osm2pgsql on it.

**Comment by mmd-osm** [comment]
I think there's plenty of other logic in your style, some of which would return before reaching the `add_z_order ` function. As the error has been reported on bangladesh-latest.osm.pbf, I'd give this 153MB download a try first (http://download.geofabrik.de/asia/bangladesh.html).

**Comment by SomeoneElseOSM** [comment]
@mmd-osm thanks - that worked (Bangladesh showed the issue before fixing style.lua and didn't afterwards).

**Pull request merged**
