### PR TITLE
Update/fix appveyor build

### PR DESCRIPTION
**Pull request by joto**

### CODE REVIEW

**Comment by lonvia** [comment]
It would be nice if somebody with access to a Windows machine could test that the exported artifact from https://ci.appveyor.com/project/openstreetmap/osm2pgsql/builds/42263001/artifacts still works.

**Comment by pnorman** [comment]
It doesn't, it can't find libexpat.dll

image

Same with proj_7_0.dll

**Comment by lonvia** [comment]
@pnorman  Could you try again with: https://ci.appveyor.com/project/openstreetmap/osm2pgsql/builds/42279394/artifacts

**Comment by pnorman** [comment]
Now missing libcurl.dll, sqlite3.dll, and tiff.dll

**Pull request merged**
