### PR TITLE
update libosmium to release version 2.5.0

### PR DESCRIPTION
**Pull request by lonvia**

### CODE REVIEW

**Comment by pnorman** [comment]
Anything in particular that needs testing?

**Comment by lonvia** [comment]
Nothing particular, no. This is just the vanilla update of libosmium. This release brings a o5m parser but I'll do the removal in another PR.

**Comment by pnorman** [comment]
Should this be boosted to 2.5.1?

**Comment by pnorman** [comment]
Builds and looks okay on my system, so it's okay to merge, but I'm holding off in case we want to go right to 2.5.1

**Comment by lonvia** [comment]
2.5.1 is not relevant for us now, although the forwarding headers might potentially be interesting in the future when we start using libosmium types internally. I can bump the version up later today.

**Comment by lonvia** [comment]
Update to libosmium 2.5.1 done.

**Pull request merged**
