### PR TITLE
Display progress while processing pending relations/ways

### PR DESCRIPTION
**Pull request by bagage**
This step is one of the biggest step with no logging, it looks like osm2pgsql is stuck but actually it is processing these pending items. Now it'll display the number of pending items left to process instead of being silent :).

### CODE REVIEW

**Comment by der-stefan** [comment]
Oh yes, this is a great feature - it can take up to days without showing progress...

**Comment by bagage** [comment]
Yeah, it looks like it's related to #862 but in the mean time it seems that even if import won't need it anymore in the future, this still might be useful for updates, so I hope it'll be merged asap, wdyt @mmd-osm @lonvia @pnorman?

**Comment by mmd-osm** [comment]
`print_stats` seems to be busy looping, maybe you want to use something like `std::this_thread::sleep_for(60s);` instead?

Also checking the queue status probably needs some additional locking via `mutex.lock();` + `mutex.unlock();` like done in `do_jobs`.

**Comment by bagage** [comment]
Thanks for reviewing this @mmd-osm, I've updated the PR accordingly!

**Comment by mmd-osm** [comment]
I didn't test your code, but this looks a bit strange. `queue.size()` is still not protected by a mutex, and I assume the queue is _not_ empty most of the time. Did you mean `while (!isEmpty)` perhaps?

**Comment by bagage** [comment]
Indeed I refactored the do/while logic right before pushing, I should have tested it. This time I tested it and it should be OK (actually removed the `isEmpty()` code, to reduce code).

**Comment by bagage** [comment]
Hey @lonvia, I did not run clang-format in the first place because it causes a lot of space diffs on the file, so I didn't want to commit these all. Maybe I applied it wrongly? 

Also, `git-clang-format` (`clang-format` actually because I could not find the former) is not fixing variables name. I don't know if it's supposed to, but I fixed it manually.

**Pull request merged**
