### PR TITLE
update to libosmium 2.3.0

### PR DESCRIPTION
**Pull request by lonvia**
- remove protobuf dependencies as libosmium now comes with its own pbf parser
- fix remaining uses of libxml2 as file format in tests

### CODE REVIEW

**Comment by pnorman** [comment]
Travis and the readme need updating to remove protobuf dependencies.

**Comment by lonvia** [comment]
Done.

**Comment by pnorman** [comment]
On my dev box

```
[pnorman@pippin /usr/home/pnorman/osm/osm2pgsql]$ createdb gis && psql -d gis -c 'create extension postgis;'
CREATE EXTENSION
[pnorman@pippin /usr/home/pnorman/osm/osm2pgsql]$ time ./osm2pgsql -O null -d gis --cache 27000 -S empty.style ~/osm/planet/canada-150520.osm.pbf
osm2pgsql SVN version 0.89.0-dev (64bit id space)

Using projection SRS 900913 (Spherical Mercator)
Allocating memory for dense node cache
Allocating dense node cache in one big chunk
Allocating memory for sparse node cache
Sharing dense sparse
Node-cache: cache=27000MB, maxblocks=3456000*8192, allocation method=3
Mid: Ram, scale=100

Reading in file: /home/pnorman/osm/planet/canada-150520.osm.pbf
Using unknown parser.

```

And it just sits there.

If I runin gdb and interrupt, I get

```
(gdb) thread apply all bt

Thread 3 (Thread 803c06800 (LWP 100903/osm2pgsql)):
#0  0x0000000802d878ba in nanosleep () from /lib/libc.so.7
#1  0x0000000802a4b64c in nanosleep () from /lib/libthr.so.3
#2  0x00000008023a1d3b in std::__1::this_thread::sleep_for () from /usr/lib/libc++.so.1
#3  0x0000000000540200 in std::__1::this_thread::sleep_for<long long, std::__1::ratio<1l, 1000l> > ()
#4  0x0000000000578364 in osmium::io::detail::ReadThread::operator() ()
#5  0x0000000000577dcd in _ZNSt3__112__async_funcIN6osmium2io6detail10ReadThreadEJEE9__executeIJEEEbNS_15__tuple_indicesIJXspT_EEEE ()
#6  0x0000000000577d85 in _ZNSt3__112__async_funcIN6osmium2io6detail10ReadThreadEJEEclEv ()
#7  0x000000000057d103 in _ZNSt3__119__async_assoc_stateIbNS_12__async_funcIN6osmium2io6detail10ReadThreadEJEEEE9__executeEv ()
#8  0x000000000057ce05 in _ZNSt3__114__thread_proxyINS_5tupleIJMNS_19__async_assoc_stateIbNS_12__async_funcIN6osmium2io6detail10ReadThreadEJEEEEEFvvEPS9_EEEEEPvSE_ ()
#9  0x0000000802a494f5 in pthread_create () from /lib/libthr.so.3
#10 0x0000000000000000 in ?? ()

Thread 2 (Thread 803c06400 (LWP 100574/osm2pgsql)):
#0  0x0000000802a548cc in __error () from /lib/libthr.so.3
#1  0x0000000802a52d8e in _pthread_cond_wait () from /lib/libthr.so.3
#2  0x00000008023ea82f in std::__1::condition_variable::wait () from /usr/lib/libc++.so.1
#3  0x00000008023a2e1b in std::__1::__assoc_sub_state::wait () from /usr/lib/libc++.so.1
#4  0x000000000057d0b8 in _ZNSt3__119__async_assoc_stateIbNS_12__async_funcIN6osmium2io6detail10ReadThreadEJEEEE16__on_zero_sharedEv ()
#5  0x00000008023d0ad0 in std::__1::__shared_count::__release_shared () from /usr/lib/libc++.so.1
#6  0x00000000005368a0 in std::__1::future<bool>::~future ()
#7  0x000000000052c067 in osmium::io::Reader::Reader ()
#8  0x000000000051f5ee in parse_osmium_t::stream_file ()
#9  0x0000000000517ea6 in parse_delegate_t::stream_file ()
#10 0x0000000000421464 in main ()
#0  0x0000000802d878ba in nanosleep () from /lib/libc.so.7
```

**Comment by pnorman** [comment]
adding `-r pbf`causes it to work

**Comment by pnorman** [comment]
Testing is showing this branch to be **much** slower

The PR
```
`which time` -l ./osm2pgsql -O null -d gis --cache 27000 -S empty.style ~/osm/planet/canada-150520.osm.pbf -r pbf
...
Node stats: total(261874403), max(3531488049) in 345s
Way stats: total(13825376), max(346632218) in 65s
Relation stats: total(214188), max(5167274) in 1s
...
Osm2pgsql took 412s overall
      411.87 real      1018.85 user        31.74 sys
   9855372  maximum resident set size
      2306  average shared memory size
        47  average unshared data size
       127  average unshared stack size
  13536167  page reclaims
         0  page faults
         0  swaps
        16  block input operations
         0  block output operations
         2  messages sent
         1  messages received
         0  signals received
    113680  voluntary context switches
     54833  involuntary context switches
```

master
```
`which time` -l ./osm2pgsql -O null -d gis --cache 27000 -S empty.style ~/osm/planet/canada-150520.osm.pbf -r
pbf
...
Node stats: total(261874403), max(3531488049) in 49s
Way stats: total(13825376), max(346632218) in 14s
Relation stats: total(214188), max(5167274) in 1s
...
Osm2pgsql took 65s overall
       65.61 real       317.41 user        37.93 sys
   9836284  maximum resident set size
      1125  average shared memory size
        43  average unshared data size
       127  average unshared stack size
   9856383  page reclaims
        28  page faults
         0  swaps
         4  block input operations
         0  block output operations
         2  messages sent
         1  messages received
         0  signals received
     38942  voluntary context switches
     80652  involuntary context switches
```

**Comment by lonvia** [comment]
I've pushed a workaround for the issue with the file format detection.

I cannot reproduce the performance issues. An import of Germany is slightly faster here on my machine. Did you see the above in multiple runs?

**Comment by pnorman** [comment]
> I cannot reproduce the performance issues.

Were you using the same options (mainly not slim)?

I'm running multiple tests now to verify.

**Comment by lonvia** [comment]
Yes, tested with null output and non-slim. I've also tried with Europe but there anything but node reading is meaningless because it starts swapping. Node reading had the same timing for master and libosmium 2.3.

**Comment by pnorman** [comment]
I am now getting a faster time, so write it off to random error.

**Pull request merged**
